//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteracoesMedicamentosas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InteracoesMedicamentosasEntities : DbContext
    {
        public InteracoesMedicamentosasEntities()
            : base("name=InteracoesMedicamentosasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Interacoes> Interacoes { get; set; }
        public virtual DbSet<Medicamentos> Medicamentos { get; set; }
    }
}
