//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteracoesMedicamentosas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interacoes
    {
        public int interacaoId { get; set; }
        public int medicamento1Id { get; set; }
        public int medicamento2Id { get; set; }
        public string reacao { get; set; }
    }
}
